;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Woodcutting",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Movement.Started",DevComment="")
+GameplayTagList=(Tag="Event.Resource.Gathering.Wood",DevComment="")
+GameplayTagList=(Tag="Event.Woodcutting.Interact",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Axe01",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.WoodCutting.Active",DevComment="")
+GameplayTagList=(Tag="Inventory.Item.Added",DevComment="")
+GameplayTagList=(Tag="Skills.Level.Woodcutting",DevComment="")
+GameplayTagList=(Tag="Skills.StaminaCost.Woodcutting",DevComment="")
+GameplayTagList=(Tag="Skills.XP.Woodcutting",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.2HSword",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Sword",DevComment="")

